name = "derp"
workers_dev = true
compatibility_date = "2025-01-17"

[build]
command = "yarn && yarn build"

[build.upload]
format = "modules"
main = "./index.mjs"

[site]
bucket = "./build"
entry-point = "dist"

[durable_objects]
bindings = [
  { name = "client_logs", class_name = "ClientLog" }
]

[[migrations]]
tag = "v1"
new_classes = ["ClientLog"]
